// StudyMate AI - Background Service Worker

// ----------------------------------------------------
// AI SERVICE LAYER (Modular and Extensible)
// ----------------------------------------------------
// To add other providers (OpenAI, Claude, etc.), simply update this service or callGeminiAPI.
async function callGeminiAPI(prompt, apiKey, model = "gemini-2.5-flash") {
    // Try both v1beta and v1 endpoints to avoid version mismatch 404 errors
    const apiVersions = ["v1beta", "v1"];
    let lastError = null;

    for (const version of apiVersions) {
        try {
            const url = `https://generativelanguage.googleapis.com/${version}/models/${model}:generateContent?key=${apiKey}`;
            
            const response = await fetch(url, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json"
                },
                body: JSON.stringify({
                    contents: [
                        {
                            parts: [
                                {
                                    text: prompt
                                }
                            ]
                        }
                    ]
                })
            });

            if (response.ok) {
                const data = await response.json();
                const candidateText = data.candidates?.[0]?.content?.parts?.[0]?.text;
                if (!candidateText) {
                    throw new Error("No response generated by the AI model.");
                }
                return candidateText;
            }

            const errorData = await response.json().catch(() => ({}));
            const errorMessage = errorData.error?.message || `HTTP error! status: ${response.status}`;
            lastError = new Error(errorMessage);

            // If it's a 404 (model not found) or similar, we retry the other API version
            if (response.status === 404 || errorMessage.toLowerCase().includes("not found") || errorMessage.toLowerCase().includes("not supported")) {
                console.warn(`Gemini API version ${version} failed for model ${model}. Retrying other versions...`);
                continue;
            } else {
                // If it's a terminal error (like bad API key or quota limit), throw immediately
                throw lastError;
            }
        } catch (err) {
            lastError = err;
            // Throw immediately if it's a terminal error
            if (err.message && (err.message.includes("API Key") || err.message.includes("blocked") || err.message.includes("No response"))) {
                throw err;
            }
        }
    }
    
    throw lastError || new Error(`Generation failed: Model ${model} not found or not supported.`);
}

const AIService = {
    async generate(text, action, customPrompt = "", settings = {}) {
        const apiKey = settings.geminiApiKey;
        if (!apiKey) {
            throw new Error("API Key not found. Please set your Gemini API Key in the Extension Settings.");
        }
        
        const model = settings.model || "gemini-2.5-flash";
        
        let prompt = "";
        switch (action) {
            // Smart Summary
            case "summary_short":
                prompt = `Summarize the following text in a concise paragraph of 2-3 sentences:\n\n${text}`;
                break;
            case "summary_bullet":
                prompt = `Provide a bulleted list summarizing the key takeaways from the following text:\n\n${text}`;
                break;
            case "summary_keypoints":
                prompt = `Extract the most important key points and concepts from the following text:\n\n${text}`;
                break;
            case "summary_exam":
                prompt = `Create comprehensive study/exam notes from the following text, highlighting important terms, definitions, formulas, and concepts in structured sections:\n\n${text}`;
                break;
            case "summary_linkedin":
                prompt = `Generate an engaging, professional LinkedIn post summarizing the core ideas from the following text. Include 3-5 relevant hashtags and emojis for readability:\n\n${text}`;
                break;
                
            // Explain Text
            case "explain_simple":
                prompt = `Explain the following text in simple, clear, and plain English, as if explaining to someone completely unfamiliar with the topic:\n\n${text}`;
                break;
            case "explain_hinglish":
                prompt = `Explain the following text in Hinglish (a natural, conversational mixture of Hindi and English written in Latin script) to make it highly relatable and simple:\n\n${text}`;
                break;
            case "explain_beginner":
                prompt = `Explain the following text at a beginner level, explaining basic terms, underlying rules, and concepts simply:\n\n${text}`;
                break;
            case "explain_professional":
                prompt = `Provide a professional, sophisticated, and industry-standard explanation of the following text, using correct terminology and business context:\n\n${text}`;
                break;
            case "explain_examples":
                prompt = `Explain the following text using clear, real-life analogies, practical examples, and everyday scenarios:\n\n${text}`;
                break;
                
            // Translate
            case "translate_hindi":
                prompt = `Translate the following text to Hindi. Ensure the translation is contextually natural, accurate, and preserves the tone:\n\n${text}`;
                break;
            case "translate_english":
                prompt = `Translate the following text to English. Ensure the translation is contextually natural, accurate, and preserves the tone:\n\n${text}`;
                break;
            case "translate_french":
                prompt = `Translate the following text to French. Ensure the translation is contextually natural, accurate, and preserves the tone:\n\n${text}`;
                break;
            case "translate_german":
                prompt = `Translate the following text to German. Ensure the translation is contextually natural, accurate, and preserves the tone:\n\n${text}`;
                break;
            case "translate_japanese":
                prompt = `Translate the following text to Japanese. Ensure the translation is contextually natural, accurate, and preserves the tone:\n\n${text}`;
                break;
                
            // Other Generators
            case "generate_notes":
                prompt = `Generate detailed, well-structured, and comprehensive learning notes from the following text. Use headers, bold terms, list items, and key callouts:\n\n${text}`;
                break;
            case "generate_flashcards":
                prompt = `Generate a set of educational flashcards (Questions and Answers) in a clear Q&A format based on the following text. Try to generate at least 3-5 flashcards.
Output format:
Q1: [Question]
A1: [Answer]
Q2: [Question]
A2: [Answer]
...
Text:\n\n${text}`;
                break;
            case "generate_quiz":
                prompt = `Generate a multiple-choice quiz based on the following text. Provide 3-5 questions. 
For each question, list option A, B, C, and D, and clearly state the correct answer with a brief explanation.
Output format:
Question X: [Question text]
A) [Option A]
B) [Option B]
C) [Option C]
D) [Option D]
Correct Answer: [Letter]
Explanation: [Reasoning]
...
Text:\n\n${text}`;
                break;
                
            // Custom Prompt / Ask AI
            case "ask_ai":
                prompt = `Answer the following question or instruction: "${customPrompt}" based on this text:\n\n"${text}"`;
                break;
                
            default:
                prompt = `Analyze the following text and explain it:\n\n${text}`;
        }
        
        return await callGeminiAPI(prompt, apiKey, model);
    }
};

// ----------------------------------------------------
// CONTEXT MENUS SETUP
// ----------------------------------------------------
chrome.runtime.onInstalled.addListener(() => {
    chrome.contextMenus.removeAll(() => {
        // Parent menu
        chrome.contextMenus.create({
            id: "studymate_root",
            title: "StudyMate AI",
            contexts: ["selection"]
        });

        // Submenu: Summarize
        chrome.contextMenus.create({
            id: "menu_summarize",
            parentId: "studymate_root",
            title: "Summarize",
            contexts: ["selection"]
        });
        const summaryTypes = [
            { id: "summary_short", title: "Short Summary" },
            { id: "summary_bullet", title: "Bullet Summary" },
            { id: "summary_keypoints", title: "Key Points" },
            { id: "summary_exam", title: "Exam Notes" },
            { id: "summary_linkedin", title: "LinkedIn Summary" }
        ];
        summaryTypes.forEach(t => {
            chrome.contextMenus.create({
                id: t.id,
                parentId: "menu_summarize",
                title: t.title,
                contexts: ["selection"]
            });
        });

        // Submenu: Explain
        chrome.contextMenus.create({
            id: "menu_explain",
            parentId: "studymate_root",
            title: "Explain Selection",
            contexts: ["selection"]
        });
        const explainTypes = [
            { id: "explain_simple", title: "Simple English" },
            { id: "explain_hinglish", title: "Hinglish" },
            { id: "explain_beginner", title: "Beginner level" },
            { id: "explain_professional", title: "Professional level" },
            { id: "explain_examples", title: "With Real-life Examples" }
        ];
        explainTypes.forEach(e => {
            chrome.contextMenus.create({
                id: e.id,
                parentId: "menu_explain",
                title: e.title,
                contexts: ["selection"]
            });
        });

        // Submenu: Translate
        chrome.contextMenus.create({
            id: "menu_translate",
            parentId: "studymate_root",
            title: "Translate Selection",
            contexts: ["selection"]
        });
        const languages = [
            { id: "translate_hindi", title: "to Hindi" },
            { id: "translate_english", title: "to English" },
            { id: "translate_french", title: "to French" },
            { id: "translate_german", title: "to German" },
            { id: "translate_japanese", title: "to Japanese" }
        ];
        languages.forEach(l => {
            chrome.contextMenus.create({
                id: l.id,
                parentId: "menu_translate",
                title: l.title,
                contexts: ["selection"]
            });
        });

        // Direct Context Options
        chrome.contextMenus.create({
            id: "ask_ai",
            parentId: "studymate_root",
            title: "Ask AI...",
            contexts: ["selection"]
        });

        chrome.contextMenus.create({
            id: "generate_notes",
            parentId: "studymate_root",
            title: "Generate Notes",
            contexts: ["selection"]
        });

        chrome.contextMenus.create({
            id: "generate_flashcards",
            parentId: "studymate_root",
            title: "Generate Flashcards",
            contexts: ["selection"]
        });

        chrome.contextMenus.create({
            id: "generate_quiz",
            parentId: "studymate_root",
            title: "Generate Quiz",
            contexts: ["selection"]
        });

        chrome.contextMenus.create({
            id: "save_highlight",
            parentId: "studymate_root",
            title: "Save Highlight",
            contexts: ["selection"]
        });
    });

    // Check for API key on install; open options page if not exists
    chrome.storage.sync.get(["geminiApiKey"], (result) => {
        if (!result.geminiApiKey) {
            chrome.tabs.create({ url: "options.html" });
        }
    });
});

// ----------------------------------------------------
// CONTEXT MENU CLICK EVENTS
// ----------------------------------------------------
chrome.contextMenus.onClicked.addListener((info, tab) => {
    if (!tab || !tab.id) return;
    
    const selectedText = info.selectionText;
    const action = info.menuItemId;
    
    // 1. Direct local action: Save Highlight
    if (action === "save_highlight") {
        chrome.storage.local.get({ highlights: [] }, (result) => {
            const highlights = result.highlights;
            const exists = highlights.some(h => h.text.trim() === selectedText.trim());
            if (!exists) {
                highlights.push({
                    text: selectedText,
                    url: tab.url || "",
                    title: tab.title || "Web Page",
                    timestamp: Date.now()
                });
                chrome.storage.local.set({ highlights }, () => {
                    chrome.tabs.sendMessage(tab.id, { 
                        type: "SHOW_TOAST", 
                        message: "Highlight saved successfully!" 
                    });
                });
            } else {
                chrome.tabs.sendMessage(tab.id, { 
                    type: "SHOW_TOAST", 
                    message: "Highlight is already saved!" 
                });
            }
        });
        return;
    }
    
    // 2. Open overlay UI on page for response displaying
    chrome.tabs.sendMessage(tab.id, {
        type: "OPEN_OVERLAY",
        action: action,
        selection: selectedText
    }, () => {
        // Suppress errors for pages where scripts cannot run
        if (chrome.runtime.lastError) {
            console.warn("Unable to inject content script overlay on this tab:", chrome.runtime.lastError.message);
        }
    });
    
    // If user clicked "Ask AI...", the UI will wait for user input. We don't trigger the API yet.
    if (action === "ask_ai") {
        return;
    }
    
    // 3. For AI actions, call API and stream/send response back
    chrome.storage.sync.get(["geminiApiKey", "model"], async (settings) => {
        try {
            if (!settings.geminiApiKey) {
                chrome.tabs.sendMessage(tab.id, {
                    type: "UPDATE_OVERLAY",
                    success: false,
                    result: "API Key not found. Please open options to set your Gemini API Key."
                });
                return;
            }
            
            const resultText = await AIService.generate(selectedText, action, "", settings);
            
            chrome.tabs.sendMessage(tab.id, {
                type: "UPDATE_OVERLAY",
                success: true,
                result: resultText
            });
        } catch (error) {
            chrome.tabs.sendMessage(tab.id, {
                type: "UPDATE_OVERLAY",
                success: false,
                result: `Error: ${error.message}`
            });
        }
    });
});

// ----------------------------------------------------
// RUNTIME MESSAGES HANDLER
// ----------------------------------------------------
chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
    if (message.type === "GENERATE_AI") {
        const { text, action, customPrompt } = message;
        
        chrome.storage.sync.get(["geminiApiKey", "model"], (settings) => {
            if (!settings.geminiApiKey) {
                sendResponse({ success: false, error: "API Key not found. Please open settings and add your API Key." });
                return;
            }
            
            AIService.generate(text, action, customPrompt, settings)
                .then(result => {
                    sendResponse({ success: true, result });
                })
                .catch(error => {
                    sendResponse({ success: false, error: error.message });
                });
        });
        
        return true; // Keep channel open for async response
    }
    
    if (message.type === "SAVE_HIGHLIGHT_DIRECT") {
        const { text, url, title } = message;
        chrome.storage.local.get({ highlights: [] }, (result) => {
            const highlights = result.highlights;
            const exists = highlights.some(h => h.text.trim() === text.trim());
            if (!exists) {
                highlights.push({
                    text: text,
                    url: url || "",
                    title: title || "Saved Snippet",
                    timestamp: Date.now()
                });
                chrome.storage.local.set({ highlights }, () => {
                    sendResponse({ success: true, message: "Highlight saved!" });
                });
            } else {
                sendResponse({ success: false, error: "Already saved" });
            }
        });
        return true;
    }
});